[package]
name = "tapp"
version = "1.0.0"
upgrade_policy = "compatible"

[addresses]
base = "0xba51c"
tapp = "0x487e905f899ccb6d46fdaec56ba1e0c4cf119862a16c409904b8c78fab1f5e8a"

[dependencies]
AptosTokenObjects = { git = "https://github.com/aptos-labs/aptos-framework.git", rev = "testnet", subdir = "aptos-token-objects" }
basic = { local = "../hooks/basic" }
advanced = { local = "../hooks/advanced" }
vault = { local = "../hooks/vault" }
